module.exports = {
    registerUser: require('./register-user'),
    authenticateUser: require('./authenticate-user'),
    retrieveUser: require('./retrieve-user'),
    updateUser: require('./update-user'),
    deleteUser: require('./delete-user'),
    createLand: require('./create-land'),
    createItem: require('./create-item'),
    retrieveItem: require('./retrieve-item'),
    searchItems: require('./search-items'),
    retrieveLand: require('./retrieve-land'),
    deleteLand: require('./delete-land'),
    searchReccommended: require('./search-reccommended'),
    updateLandDivisions: require('./update-land-divisions'),
    updateLandPlanted: require('./update-land-planted'),
    updateItem: require('./update-item'),
    updateItemHarvested: require('./update-item-harvested'),
    updateItemPlanted: require('./update-item-planted'),
    retrieveUserVeggies: require('./retrieve-user-veggies'),
    retrieveLandPlantations: require('./retrieve-land-plantations'),
    retrieveItemForUser: require('./retrieve-item-for-user'),
    retrieveUserLands: require('./retrieve-user-lands'),
    deleteVeggieFromLand: require('./delete-veggie-from-land'),
    retrieveInterval: require('./retrieve-interval'),
    retrieveAllItems: require('./retrieve-all-items'),
    updateItemAdd: require('./update-item-add'),
    retrieveUserPlantations: require('./retrieve-user-plantations')
}